### PR TITLE
Add Notification dark theme.

### PR DESCRIPTION
**Pull request by Viperusgit**
If you look into my fork (sloppy coding with some redundancies) you will find I have implemented a dark mode option for notifications and I would be grateful if you either A. merged it with the master or B. rewrite it yourself. btw I am new to github I don't want to merge all 17 commits If you look at what I changed you can pick and choose what you need.

### CODE REVIEW

**Comment by wasdennnoch** [comment]
"Removed useless settings" eh? Yes, I'll copy the parts I need in some hours.
This is the first part of the general dark theme, thanks! :D

**Comment by Viperusgit** [comment]
Thank you!! yes if you check you will see I had a comment on the original commit where I had removed the "app" category that it is useless in my case because 1.nova has its own application hider 2.I would feel wrong sending you debug logs from my custom build where I most likely caused errors. (would be nice if I could get just a small bit of credit for dark theme preference tho)

**Comment by wasdennnoch** [comment]
Yeah, but not everyone uses nova launcher and the logs from your build should be the same when you don't add or remove debud calls. I already copied the important parts, but the text color is still black, have to change that. I can give you cradits if you want.

**Comment by Viperusgit** [comment]
alright closing my pull... I plan on updating my own stuff and considering I set this pull from my master I guess it would be wrong for me to keep it open :P

**Pull request closed without merging**
