### PR TITLE
Update zh-rCN strings

### PR DESCRIPTION
**Pull request by haseoxth**

### CODE REVIEW

**Comment by wasdennnoch** [comment]
The translations are moved to Crowdin now, no need for a pull request (I see you are already adding Strings on Crowdin) ;)

**Comment by wasdennnoch** [comment]
And you don't have to modify the translated strings, they get overwritten when I export them. The only ones that have to look nice are the original ones ;)

**Comment by haseoxth** [comment]
Sorry sir, but what does the "don't have to modify the translated strings" mean exactly? I modified some translated strings which are not translated by me before, since there are several grammar mistakes with them.
And now I see you don't receive translation PR anymore, this means we will not have instant build with translated strings from now on but period release instead? I'm sorry if this is asked before, but what's your plan for translating in future?

**Comment by wasdennnoch** [comment]
As you can see in 4f71235f8d89e9975c920ac67db5e0b1bb454189 the files I download from Crowdin are already properly formatted ;)

**Pull request closed without merging**
