### PR TITLE
Use interpolators that are similar to DP4 to prevent QS icon overlap

### LINKED ISSUE #359: Overlapping QuickQS isons in animation
screenshot_20160601-234629

### PR DESCRIPTION
**Pull request by vemacs**
Fixes #359

### CODE REVIEW

**Comment by vemacs** [comment]
I think the icon text interpolators need to be adjusted as well, don't merge yet

**Comment by vemacs** [comment]
@wasdennnoch Note that the text labels are off. I tried setting the same interpolator (and a quintic one) to builder4 and builder5 with some small effects, but they overlap the icons a bit.

**Comment by wasdennnoch** [comment]
I'll experiment around with that

**Comment by vemacs** [comment]
I think setting builder4 to just return 1 might work. Testing.

**Comment by paphonbth** [comment]
Yes, the text labels positions are relative to QS container. So we need to add the container height to the animator to keep them stay at almost the same position and animate it toward to the header tiles.

See [this](https://github.com/wasdennnoch/AndroidN-ify/blob/master/app/src/main/java/tk/wasdennnoch/androidn_ify/systemui/qs/QuickQSPanel.java#L140).

**Comment by vemacs** [comment]
Changing builder5 transition to start from gridHeight seems to be an okay hack to resolve the overlapping.

**Comment by vemacs** [comment]
Yep, 

            builder5.addFloat(qsTileView, "translationY", gridHeight - StatusBarHeaderHooks.mQsContainer.getPaddingBottom(), 0f);

and 

        builder2.setStartDelay(0.85f);

Seem to aesthetically resolve the overlap issues.

**Comment by wasdennnoch** [comment]
I'm currently copying a class from the decompiled source to optimize the animation a bit.

**Pull request merged**
