### PR TITLE
Update Ukrainian translation

### PR DESCRIPTION
**Pull request by Electroz**

### CODE REVIEW

**Comment by wasdennnoch** [comment]
Would it be possible to copy the changes directly to crowdin? I can still merge it if you want, but then I'll have to upload them manually to crowdin.
https://crowdin.com/project/android-n-ify

**Comment by Electroz** [comment]
You can upload the file to the crowdin?

**Comment by wasdennnoch** [comment]
I can merge this and then upload the uk strings file to crowdin. Or you can do this too if you want to.

**Comment by Electroz** [comment]
Ok. Can you do me a proofreader, so I confirmed the translation?

**Comment by wasdennnoch** [comment]
isn't a proofreader supposed to understand the language he's dealing with? Or am I misunderstanding?

**Comment by Electroz** [comment]
http://image.prntscr.com/image/4f1def02e82b452d9a91b0b04f46dbcd.png

**Comment by Electroz** [comment]
https://support.crowdin.com/for-translators/onlineworkbench/proofreading/

**Comment by wasdennnoch** [comment]
Oh, that's what you mean. It isn't necessary to confirm translations, I disabled the requirement (because there aren't enough people who would read them ^^).

**Pull request closed without merging**
