### PR TITLE
Fix CM QS edit panel

### PR DESCRIPTION
**Pull request by paphonbth**

### CODE REVIEW

**Comment by paphonbth** [comment]
Added option to change max tiles count (so users with small screen won't end up with overlapping tiles)

**Comment by paphonbth** [comment]
This breaks functionality on non-CM ROMs.
Closed pull request until fixed.

**Comment by SirHydarnes** [comment]
Well, can't you enable it and add a warning so people who don't have cm installed wouldn't use it?

**Comment by SirHydarnes** [comment]
Never mind. I just saw the new pull

**Comment by paphonbth** [comment]
Actually the problem isn't about enabling the fix.
It's about the fix that runs regardless of enabled or not.
Anyway, It seems like my latest commit fixed it so I created a new PR and it got merged.

**Pull request closed without merging**
