### PR TITLE
Direct reply layout improvements and crash fix in settings

### PR DESCRIPTION
**Pull request by Maxr1998**

### CODE REVIEW

**Comment by wasdennnoch** [comment]
But if the app doesn't specify a color no color will be used. The header color gets generated if none is specified.

**Comment by Maxr1998** [comment]
Oh, so the private app name's color can be different from the other color?

**Comment by wasdennnoch** [comment]
If the app doesn't send a color with the notification it will be generated from the app icon and then set onto the app name while the color field stays unmodified. So yes, if the app doesn't supply one it's different. And the background would be black.

**Comment by Maxr1998** [comment]
I see. Couldn't we set the generated color onto the notification? Or should I revert the changes?

**Comment by Maxr1998** [comment]
Ugh. Didn't want to have this in a single commit.
But can't fix anymore...

**Comment by wasdennnoch** [comment]
We could set it, but we don't need it anymore, so it's okay that way right now.

**Pull request merged**
