### PR TITLE
Brightness slider position & Date-Time expanded text size change  and added warning dialog before restarting SystemUI  

### PR DESCRIPTION
**Pull request by amansingh63**
To give a more look-alike of Android N notification Panel

Show a warning dialog before restarting SystemUI

### CODE REVIEW

**Comment by wasdennnoch** [comment]
Most dimensions are extracted out of the decompiled apks, the expanded size is exactly the same as in the preview. Have to take a look at the brightness slider padding first.

**Comment by amansingh63** [comment]
I also decompessed android n systemui apk.. the font size for date and time when expanded is 16sp as i change in the commit... but for brightness slider i used android N screenshot and found that brightness slider should be uplifted so i removed th top paddin to make it totally look alike that of android n previews..

**Comment by wasdennnoch** [comment]
You didn't import the dialog classes...

**Comment by lovep10** [comment]
9e9ce7c

**Pull request merged**
