### PR TITLE
Emergency Info

### PR DESCRIPTION
**Pull request by paphonbth**

### CODE REVIEW

**Comment by wasdennnoch** [comment]
Shouldn't we wait until after the next release with that? I don't want to squeeze tons of new features into the new version, I'd like to optimize the current features and add this here after everything is working properly.

**Comment by paphonbth** [comment]
This feature is just a simple hook that will show an activity, nothing complex. It's even simpler than the app theming feature.
But anyway, it doesn't work on Lollipop.

**Comment by wasdennnoch** [comment]
Lollipop support should be easy, in theory you just have to add a button to the dialer like in M.

**Comment by paphonbth** [comment]
Sorry if I'm too late to answer this. But M already has a hidden button. All I do is enabled it.

**Pull request closed without merging**
