### PR TITLE
Bring back tap to add tiles

### PR DESCRIPTION
**Pull request by paphonbth**

### CODE REVIEW

**Comment by wasdennnoch** [comment]
I just added the specs myself in the brute forcing method

**Comment by wasdennnoch** [comment]
What do you mean by "not working"?

**Comment by paphonbth** [comment]
It just doesn't do anything with those specs added (no icon, no label, no visible tile). I might need to look into CM source again.

**Comment by wasdennnoch** [comment]
They are working for me.

**Comment by paphonbth** [comment]
You mean those that I've added later? (LiveDisplay, SU, ADB, etc.)

**Comment by wasdennnoch** [comment]
adb, themes and LiveDisplay are showing up and working. Yeah, RR reverted some changes made in CM.

**Comment by wasdennnoch** [comment]
I just remembered something: You are removing any tile that isn't static, but the 6 tiles are dynamic tiles, so they get removed. Why do you remove them in the first place? Are they somewhat different?

**Comment by paphonbth** [comment]
It will be there in QS Panel on boot and will disappear after editing tiles. So I removed it.

**Pull request merged**
