### PR TITLE
Remove rounded corners from QS background container

### PR DESCRIPTION
**Pull request by vemacs**
Fixes https://github.com/wasdennnoch/AndroidN-ify/issues/173

Before:

After:

### CODE REVIEW

**Comment by wasdennnoch** [comment]
The problem is that this method uses the fixed primary color and is not themable; I'll implement a method that fetches the color from the SystemUI in a few hours.

**Comment by vemacs** [comment]
Oh. The original XML declaration does use the fixed primary color, however: https://android.googlesource.com/platform/frameworks/base/+/eb2727b/packages/SystemUI/res/drawable/qs_background_primary.xml

**Comment by wasdennnoch** [comment]
Yes, it gets the color from the SystemUI color file whis is themable. This method gets the color from my own colors file which isn't affected by theming.

**Comment by vemacs** [comment]
Looks like I need to learn more about how resources are loaded. Thanks.

**Comment by wasdennnoch** [comment]
Forwarded resources are completely handled by the modules resources ;)

**Pull request closed without merging**
