### PR TITLE
Fix for SW double-tap speed settings

### PR DESCRIPTION
**Pull request by rdmrocha**
SW module was not reacting to changes in double-tap speed value. abstracted it and moved the broadcast receiver to the parent class. also, these values were not being read on module load.

took the opportunity to update pt_PT string as well

### CODE REVIEW

**Comment by wasdennnoch** [comment]
Looks good, but in the preferences.xml you set the default value to 120 and not 180. You seem to be a very fast clicker ;)
The strings are in a wrong order, but that's not that important. Instead of using cdata you could also just escape the ampersand with "&amp;".

Do you have some experience with inter-process communication? I had the following problem:
The BroadcastReceiver properly received the changed value of the "Fix Sound- & Notif tile" preference and set the value via `SummaryTweaks.sFixSoundNotifTile = <new value>`. But when I opened the settings app, `sFixSoundNotifTile` still had the previous unchanged value, and it would keep this value no matter what I did.

**Comment by rdmrocha** [comment]
let go in order:

in terms of speed, I was going for something that was clickable for the app switch, but still fast enough for the regular recents menu to show up (400ms was a very noticeable delay)

the strings where translated using android studio's internal translate tab. have no idea if it messes up the order but that is 100% transparent for the app side

regarding the ampersand, was under the idea android studio was doing those automatically, if not, I can double-check and fix it

I haven't explored the sFixSoundNotifTile but I can take a look to check what might be happening. will ping back in a while

**Comment by rdmrocha** [comment]
by the way: I'm getting these errors in android studio:

/Users/rrocha/code/AndroidN-ify/app/src/main/res/drawable/arrow_down.xml
Error:(4, 23) No resource found that matches the given name (at 'src' with value '@drawable/arrow_down_alpha').
/Users/rrocha/code/AndroidN-ify/app/src/main/res/drawable/arrow_up.xml
Error:(4, 23) No resource found that matches the given name (at 'src' with value '@drawable/arrow_up_alpha').

working around them changing the drawables temporarily to android:drawable/arrow_down_float and android:drawable/arrow_up_float

are you using drawables that you forgot to check-in into github?

**Comment by wasdennnoch** [comment]
Oh, yes, the drawables didn't get committed because I added the files directly and not via AS, kind of a stupid setting to automatically exclude them. 

I think the problem with the variable is that every process has its own ClassLoader and therefore the system server and the settings app basically modify two different versions of the file.
I'll probably make the fix-tile setting only beig applied at boot because IPC isn't working that easy and reloading the settings every time "can be quite expensive with SELinix enforcing". Also the user probably won't ever again change this setting.

**Comment by rdmrocha** [comment]
OK: so your problem with the sFixSoundNotifTile is that that value is only used by afterLoadCategoriesFromResource and this xposed method is called on on module load. So regardles of the changes, you'll only apply them after a reboot. Will take a look at the xposed lib to check weather those changes can be made in runtime easily

**Comment by wasdennnoch** [comment]
I removed the code with the BroadcastReceiver, so you can't see ot here; basically there was another case-statement in the BR that changed the value in SummaryTweaks

**Comment by wasdennnoch** [comment]
Thanks for your help, but I think I'll just set this bool on startup and that's it. It probably won't get changed often.

**Pull request merged**
