### PR TITLE
Notifications rework

### LINKED ISSUE #732: Some notifications that should be unexpandable can be expanded, making them smaller
Couldn't think of a better title, but here's what I mean:
https://gfycat.com/HorribleKaleidoscopicFlatcoatretriever

### LINKED ISSUE #1267: Progress bar issue
**Description**
I know this issue was fixed. But my progress bar is still short.
**Module version (build version)**
Latest build 792.
**Xposed log / logcat**

### LINKED ISSUE #1268: Music Player notification issue
I can't see the singer's name nor the album name because an white bar is overlapping the text. I tried to use another media player but I get the same thing and this happens only on the lockscreen
screenshot_20161213-133702

### PR DESCRIPTION
**Pull request by numeprenume**
Fixes #1267
Fixes #732
Fixes #1268

### CODE REVIEW

**Comment by paphonbth** [comment]
This should fix the problem, but then the users will complain about right icon overlapping the progress bar.

**Comment by numeprenume** [comment]
Oh crap, yeah, I haven't thought that there were notifications that did that. What apps have a right icon and a progress bar?

**Comment by numeprenume** [comment]
Okay, this should fix the progress bar issues once and for all. Also fixes a plethora of other issues related to the notifications and makes them pixel-identical to the notifications in N.

**Comment by yzyboost** [comment]
@wasdennnoch @paphonbth @Maxr1998

**Comment by wasdennnoch** [comment]
Not sure if increasing the Xposed SDK version does anything useful but it also shouldn't break anything.

**Comment by numeprenume** [comment]
Yeah I just did it cause AS kept bugging me with it and it didn't break anything anyway.

**Pull request merged**
