### PR TITLE
Italian strings.xml update

### PR DESCRIPTION
**Pull request by SlimShadys**

### CODE REVIEW

**Comment by SlimShadys** [comment]
Oh, sorry. Didn't see the crowdin thing. Will upload there :)

**Comment by wasdennnoch** [comment]
No problem :)

**Comment by SlimShadys** [comment]
@wasdennnoch https://github.com/wasdennnoch/AndroidN-ify/commit/6e2fdf5e9199a46abe16c36d988cbecaeba8f537 I can't find these strings in crowdin italian page :c

**Comment by wasdennnoch** [comment]
https://crowdin.com/translate/android-n-ify/1/en-it#205
https://crowdin.com/translate/android-n-ify/1/en-it#206
https://crowdin.com/translate/android-n-ify/1/en-it#207
? :P

**Comment by SlimShadys** [comment]
I'm drunk :S

**Pull request closed without merging**
