### PR TITLE
Fix notifications background on lockscreen

### PR DESCRIPTION
**Pull request by numeprenume**
- Also fixes ambient display with notifications background

- Added option to change notification colors

- Small bug fixes

Pretty sure this is not the most efficient way of doing this, but I'm open to suggestions.

### CODE REVIEW

**Comment by yzyboost** [comment]
@paphonbth @wasdennnoch

**Comment by yzyboost** [comment]
@Maxr1998

**Comment by yzyboost** [comment]
merge, merge.

**Comment by zamzameir** [comment]
@numeprenume do you have a compiled version for this? mind sharing?

**Comment by zamzameir** [comment]
@yzyboost this project is long time dead bro

**Comment by ACHOKAMAN** [comment]
I don't think they will be major fixes...this project was abandoned only
few intrested devs support otherwise just try bear with it...

**Comment by numeprenume** [comment]
@zamzameir [here](https://drive.google.com/open?id=0B7NA3219RnozaFFQQVBOZmNpN1E)

**Pull request merged**
