### PR TITLE
"Custom Quick Settings" support

### PR DESCRIPTION
**Pull request by paphonbth**
Add support for broadcast tile used by apps like "Custom Quick Settings"

### CODE REVIEW

**Comment by wasdennnoch** [comment]
You can merge them yourself now ^^

**Comment by paphonbth** [comment]
I can't. It says I don't have write access to this repo.

**Comment by wasdennnoch** [comment]
Did you get an e-mail that I added you yesterday?

**Comment by wasdennnoch** [comment]
You didn't accept it, that's why.

**Comment by paphonbth** [comment]
Somehow the Outlook doesn't notify me and I forgot to check my mail. My fault.

**Pull request merged**
