### PR TITLE
Fix #120

### LINKED ISSUE #120: [Bug] Sometimes there are two overlapping ripples for the expand panel button
I can't reproduce this consistently, but here's a screenshot of the issue:

Running latest revision on stock 6.0.1.

### PR DESCRIPTION
**Pull request by vemacs**
The code is bad but it works

### CODE REVIEW

**Comment by wasdennnoch** [comment]
Let me try another method that doesn't recreate the view every time first ^^

**Comment by vemacs** [comment]
I tried resetting the foreground (there was no change), resetting the background (setting it to resID 0 "fixes" the dual ripple by nuking all ripples and setting it back brings back the issue), resetting all of the initially set boolean values, checking linked touchables, resetting the ImageDrawable, so on and so forth. None of them worked, to save you the time.

**Comment by wasdennnoch** [comment]
What about setting the parent view to setEnabled(false)?

**Comment by vemacs** [comment]
Didn't think of that. However, as I am removing and readding this to the parent view, would it change things?

**Comment by vemacs** [comment]
Tried setting mHeader from NotificationPanelHooks to disabled at the end of handleShowingDetail, has no effect.

**Comment by wasdennnoch** [comment]
Know what? I just tested my indicator and is has the same issue for the first time. It indeed looks like the indicator itself has two backgrounds. The normal ripple and the square background which has no ripple effect and kinda looks like the background of a disabled view.
The only thing I noticed in the hierarchy viewer is that the view has the same ID as a style of the SystemUI, but that shouldn't be a problem. Another thing is that the bugged view had the layer type set to hardwhere, whereas after a restart the layer type is none. Let me try experimenting with the layer type a bit.

**Comment by wasdennnoch** [comment]
Yep, the issue is the hardware layer type. I don't know what is modifying the layer types, but it should be fixed by setting the layer type on every click.

**Comment by wasdennnoch** [comment]
Fixed with 8a7f5a4f37ff3339154289de977a1c5b5119aa1e. Thanks for your help though!

**Comment by vemacs** [comment]
Wow, that's a cleaner solution by far!

**Pull request closed without merging**
