### PR TITLE
Fixes #510

### LINKED ISSUE #510: Slightly "off" positioning and other minor issues with fancy QS animation on stock
At the end of the animation on stock 6.0, the QS icons jump a bit. 

Here is an screenshot from somewhere close to the last frame of the animation (also note the scrunched LTE icon): http://i.imgur.com/uL9sWoq.png

Here is a screenshot of the expanded QS panel: http://i.imgur.com/hvEwsBQ.png

Open them in separate tabs and switch between the tabs to see what I mean by "jumping". The vertical height seems to be off by around 4dp (visually, it seems close to the height of the text...)

Another thing is that the animation fails to show up at all after opening and closing the tiles editor.

### PR DESCRIPTION
**Pull request by vemacs**
Not sure if this breaks the offset on CM-based ROMs, but it fixes it for me on AOSP.

### CODE REVIEW

**Comment by wasdennnoch** [comment]
I'll test it first; I'm using a dimension replacement to set the top padding to -6dp,so shouldn't be the tiles shifted up even more?

**Comment by numeprenume** [comment]
I can confirm that it works, but only in portrait mode. (on an AOSP-based ROM)

**Comment by vemacs** [comment]
Not sure why it works, but it does (in portrait). Compensation for the x translation will be needed in landscape mode.

**Comment by vemacs** [comment]
Landscape actually is just all-around glitchy, and has nothing to do with the padding adjustment. It looks like setupAnimators isn't even called (according to my logs) on orientation change/panel expand, and the animation doesn't even start until the panel is halfway closed. Not sure how easily fixable that is.

**Comment by wasdennnoch** [comment]
Landscape is broken in Android itself, sometimes the panel just snaps to randon positions when dragging. That the animation starts too late is also related to Android because if the panel is taller than the screen (i.e. landscape) you can drag the panel allowing you to access all QS. I'll have a look at how it behaves in the developer preview, wouldn't wonder is it's broken there too.

**Comment by vemacs** [comment]
Maybe just disable the fancy transition on landscape for now. I personally hardly ever use landscape.

**Comment by wasdennnoch** [comment]
Made a little video about how the QS behave in N, and yep, it's even broken there, but they added something else: https://youtu.be/AiPPo2xUzdo

**Comment by wasdennnoch** [comment]
Now I noticed that the icons jump upwards after the animation. Oh well.

**Comment by wasdennnoch** [comment]
The icons only jump when the notification shade is taller than the screen (when you can scroll through the panel / notifications), otherwise it's working fine.

**Pull request merged**
