### PR TITLE
Please create strings.xml SK

### PR DESCRIPTION
**Pull request by ja-som**

### CODE REVIEW

**Comment by wasdennnoch** [comment]
`translatable="false"` means that you don't have to copy the string into a translated strings file ;)
Can you remove this line? Otherwise, thanks!

**Comment by ja-som** [comment]
I always leave all strings in file, so I can check in the future if some are missing. But yes, I can remove it, but I don´t know how, on this state. Can you please merge it, then I will send another pull request, or delete this one and I will send it again :)

**Comment by wasdennnoch** [comment]
You can still push changes to your fork, they should be added to this pull request automatically.

**Comment by ja-som** [comment]
New commit was created, I hope it is OK :)

**Pull request merged**
