### PR TITLE
QS improvements

### PR DESCRIPTION
**Pull request by paphonbth**
- Paged tile layout
- Better animations

### CODE REVIEW

**Comment by tsynik** [comment]
I have issues with Fancy QS Tiles animations on Sony's ZL official 5.1.1 build (latest). QS Tiles can't be edited in any way (except Sony's editor via their missaligned button), and icons 4rth 5th 6th go to wrong postions on panel open (Wi-Fi, BT and GPS are animated correctly).

**Comment by wasdennnoch** [comment]
@tsynik just pushed a fix.

**Comment by tsynik** [comment]
Strange, but Build621 didn't fixed this error on my phone. Still boot loop.

**Comment by tsynik** [comment]
The only actual issue with Build624 on Sony Xperia ZL 5.1.1 ROM with disabled QS editor is position of native editor button in header (can be hided with "Hide edit tiles button") and white spaces on KeyGuard view  / doesn't working "Enlarge first row" setting.

**Pull request merged**
