### PR TITLE
New notification header

### PR DESCRIPTION
**Pull request by paphonbth**
Still working on many new features such as expand indicator,
notification drawer background, etc.

### CODE REVIEW

**Comment by wasdennnoch** [comment]
Man, that lioks awesome :D

**Comment by hrithikb** [comment]
What's new sir?

**Comment by wasdennnoch** [comment]
Nothing really new on the frond end yet, only the code got changed to match the implementation in N.

**Comment by paphonbth** [comment]
Ended up with a SystemUI crash loop and couldn't get a log because I'm not at my PC right now.

**Comment by hrithikb** [comment]
Sir, the build with the new notifications header id creating problems with app icon in notification so i moved to 530 Build

**Pull request merged**
