### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by haseoxth**

### CODE REVIEW

**Comment by wasdennnoch** [comment]
How many pull requests do you want to create xD

**Comment by haseoxth** [comment]
Sorry for that, I'm trying to learn how to use some function in github and make some mistakes...

**Comment by wasdennnoch** [comment]
btw you can add as many commits as you want to, I have an option to squash them into one single commit

**Comment by haseoxth** [comment]
Got it, thanks :)

**Pull request closed without merging**
