### PR TITLE
Add support to TaskManager header item for Resurrection Remix MM

### PR DESCRIPTION
**Pull request by mariozawa**

### CODE REVIEW

**Comment by wasdennnoch** [comment]
The pull request contains all the changes of the previous one?

**Comment by mariozawa** [comment]
No. It is only included in the pull request.

**Comment by wasdennnoch** [comment]
Yes, but they shouldn't be, I already merged that request... Your PR should only contain your changes.

**Comment by wasdennnoch** [comment]
Implemented with 42343a9972f756eb6a044c9e6fd3b7a35681141c

**Pull request closed without merging**
