### PR TITLE
New NotificationPanel layout, new PackageInstaller, StackScrollAlgorithm fixes and more

### PR DESCRIPTION
**Pull request by numeprenume**
I can't even remember all the things I've done here.

### CODE REVIEW

**Comment by wasdennnoch** [comment]
You should create a new fork after that to update it and remove all the old commits lol. Let's hope it merges well.

**Comment by wasdennnoch** [comment]
The build failed because you missed escaping an '. Lemme see.

**Comment by numeprenume** [comment]
Oh crap, yeah. I have no idea how I missed that before the apostrophe.

**Comment by wasdennnoch** [comment]
I pushed a fix, it should build now (at least it did for me).

**Comment by numeprenume** [comment]
Found another problem. Trying to fix it ASAP.

**Pull request merged**
