### PR TITLE
Remove rounded corners from QS background container

### PR DESCRIPTION
**Pull request by vemacs**
I haven't tested the themability, but it doesn't throw an exception, which means that it should be good.

### CODE REVIEW

**Comment by wasdennnoch** [comment]
The getIdentifier way is the right approach :)
But you can do it even easier: Remove the resource replacement and instead of setting the color on the ShapeDrawable just set the color directly on the mQsContainer ;)

**Comment by vemacs** [comment]
I may be dumb, but wouldn't the rounded corners pop back up (even with the 0dp radius) if the resource replacement was removed?

**Comment by wasdennnoch** [comment]
Setting the background color overrides the drawable background (internally it sets a new ColorDrawable as the background)

**Comment by vemacs** [comment]
Would changing the type of the background cause incompatibilities?

**Comment by wasdennnoch** [comment]
It shouldn't as the background never gets modified.

**Comment by vemacs** [comment]
Modified PR to do that :+1:

**Comment by vemacs** [comment]
Heads up, CI build has failed ever since RecyclerView support lib was bumped: http://ci.paphonb.xyz/job/AndroidN-ify/121/console

**Comment by wasdennnoch** [comment]
That's weird, I updated to the new version in the SDK manager yesterday. They probably didn't update the docs yet and he didn't update his SDK tools yet. I'll revert the update for now.

**Pull request merged**
